### GENERAL SETTINGS ###

title: Concrete Canoe
description: "The University of Toronto Concrete Canoe Team is a multi-disciplinary design team completely managed by students. As you may expect we take concrete, a really dense and tensilely weak material, and turn it on its head. When we are done with it, we have concrete that is not only good in tension but also less dense than water! Each year we design, test, and construct our own canoe to pit it against other universities annually and aim to place among the top concrete canoe teams."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
senpai: Henry Lu

markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FFC90E" #"#00b3fe" 
  primary_rgb: "250,250,250" # "0,179,254"#rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#33004D" #"#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"

exclude: ['README']  

### CONTACT SETTINGS ###

social:
  - title: facebook
    url: https://www.facebook.com/University-of-Toronto-Concrete-Canoe-Team-213195255385780/
  - title: twitter
    url: https://twitter.com/utcanoe
  - title: envelope
    url: mailto:ut.canoe@gmail.com

address:
  - lines: 
    - 704 Spadina Ave,
    - Toronto, Ontario
    - Canada

email: ut.canoe@gmail.com

### OTHER DATA ###
    
members:
  - name: James Yip-Albin
    position: Project Manager 
    img: james.jpg
  - name: Cory Sulpizi
    position: Project Manager
    img: cory.jpg
  - name: Andy Zhao
    position: Concrete Lead
    img: andy.jpg
  - name: Matthew Garcia
    position: Concrete Lead
    img: matthew.jpg
  - name: David Gerhardt
    position: Strutural Lead
    img: david.jpg
  - name: Liam MacKichan
    position: Structural Lead
    img: liam.jpg
  - name: Machenzie de Carle
    position: Hull Lead
    img: mackenzie.jpg
  - name: Carole Suarez
    position: Paddling Captain
    img: carole.jpg
  - name: Henry Lu
    position: Webmaster
    img: henry.jpg
    social:
        - title: envelope
          url: mailto:henry.lu@mail.utoronto.ca
  - name: Dale Gottlieb
    position: Sponsorship Director
    img: dale.jpg
  - name: Allan Song
    position: Treasurer
    img: allan.jpg
  - name: Ron Suprun
    position: Finishing Manager
    img: ron.jpg
  - name: Gabriel Wolofsky
    position: Construction Manager
    img: gabriel.jpg

sponsors:
  - name: "U of T Civil Engineering"
    img: "civ.png"
    url: "http://www.civil.engineering.utoronto.ca/"
  - name: "U of T Engineering Society"
    img: "skule.png"
    url: "http://skule.ca/about-skule/"
  - name: "U of T Engineering Alumni"
    img: "alumni.png"
    url: "http://my.alumni.utoronto.ca/s/731/index.aspx?sid=731&gid=36"
  - name: "BASF (Materials)"
    img: "basf.png"
    url: "http://www.basf.com/group/corporate/en/index"
  - name: "EllisDon"
    img: "ellisdon.png"
    url: "http://www.ellisdon.com/"
  - name: "Foam Concept (Materials)"
    img: "foam.png"
    url: "http://www.foamconcept.ca/en/home/"
  - name: "Lafarge North America (Materials)"
    img: "lafarge.png"
    url: "http://www.lafarge-na.com/"
  - name: "RMCAO"
    img: "rmcao.png"
    url: "http://rmcao.org/"
  - name: "Scofield (Materials)"
    img: "scofield.png"
    url: "http://www.scofield.com/"
  - name: "U of T Mechanical & Industrial Engineering"
    img: "mie.png"
    url: "https://www.mie.utoronto.ca/"
  - name: "U of T Students' Union"
    img: "utsu.png"
    url: "http://www.utsu.ca/"
