### GENERAL SETTINGS ###

# Site settings
title: Concrete Canoe
description: "The University of Toronto Concrete Canoe Team is a multi-disciplinary design team completely managed by students. As you may expect we take concrete, a really dense and tensilely weak material, and turn it on its head. When we are done with it, we have concrete that is not only good in tension but also less dense than water! Each year we design, test, and construct our own canoe to pit it against other universities annually and aim to place among the top concrete canoe teams."
analytics: #Google analytics code in the format XX-nnnnnnnn-n

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FAE632" #"#00b3fe" 
  primary_rgb: "250,230,50" # "0,179,254"#rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#4090FF" #"#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#111"

exclude: ['README']  

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/University-of-Toronto-Concrete-Canoe-Team-213195255385780/
  - title: twitter
    url: https://twitter.com/utcanoe
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 704 Spadina Ave,
    - Toronto, Ontario
    - Canada
email: ut.canoe@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
      - title: facebook
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Chemical Engineering
    img: chem.jpg
    url: chem.com
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
