### SITE SETTINGS ###
title: Concrete Canoe
senpai: Henry Lu
analytics: #Google analytics code in the format XX-nnnnnnnn-n
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
baseurl: ""
exclude: ['README','.htaccess']

### THEME SETTINGS ###

colors:
  primary: "#FFC90E"			#default 00b3fe 
  primary_rgb: "250,250,250"	#default 0,179,254  
  secondary: "#33004D"			#default 384452, 19827D
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"

### OTHER SETTINGS ###

description: "The University of Toronto Concrete Canoe Team is a multi-disciplinary design team completely managed by students. As you may expect we take concrete, a really dense and tensilely weak material, and turn it on its head. When we are done with it, we have concrete that is not only good in tension but also less dense than water! Each year we design, test, and construct our own canoe to pit it against other universities annually and aim to place among the top concrete canoe teams."

social:
  - title: facebook
    url: https://www.facebook.com/University-of-Toronto-Concrete-Canoe-Team-213195255385780/
  - title: twitter
    url: https://twitter.com/utcanoe
  - title: envelope
    url: mailto:ut.canoe@gmail.com

address:
  - lines: 
    - 704 Spadina Ave,
    - Toronto, Ontario
    - Canada

email: ut.canoe@gmail.com